name: "mihir_data_modeling"
version: "0.1.0"

profile: dbt_mihir

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  mihir_data_modeling:
    materialized: table
    marts:
      employee:
        utils:
          schema: utils
      region_territories:
        utils:
          schema: utils
